module.exports =  Object.freeze({
    ADD_SCHEDULE : "ADD_SCHEDULE",
    DELETE_SCHEDULE: "DELETE_SCHEDULE",
    ACTIVE_SCHEDULE: "ACTIVE_SCHEDULE",
    DEACTIVE_SCHEDULE: "DEACTIVE_SCHEDULE",
})